services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chat_db
      PGDATA: /data/postgres
    volumes:
      - gw2_chat_postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-example@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - gw2_chat_pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
volumes:
  gw2_chat_postgres:
  gw2_chat_pgadmin:
