spring:
  application:
    name: Enchanted Message Bridge
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
  jpa:
    show-sql: ${SHOW_SQL_LOG:false}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  level:
    org:
      hibernate:
        SQL: ${HIBERNATE_LOG_LEVEL:INFO}
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

file:
  upload-path: ${FILE_UPLOAD_PATH:/home/kakan/Workspace/gw2-poc-chat-system/uploads/}

web:
  config:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}